### ISSUE TITLE
MVTs not showing on deployed website

### ISSUE THREAD

**Issue by Robinlovelace** [qfes/rdeck#78]
Hi {rdeck} developers, I've just been playing with this and it seems like a great package, thanks for putting it out there!

I've got some vector tiles working properly but the problem is they only seem to be visible when the html is on my local computer.

Here's an example of the deployed web version, which has nothing in Dublin when you zoom in: https://jazzy-elf-95a68a.netlify.app/index-test.html

But when you download the underlying html you can see the MVP. Any ideas of the cause and how to work around this?

I'm also having issues styling the data but will save that for another day and possibly another issue.

**Comment by Robinlovelace** [comment]
P.s. here's a reproducible example that can generate the map and the html. Can provide further details.

```r
remotes::install_github("qfes/rdeck")
library(rdeck)

# tiles = tile_json(tileset_id = "https://api.mapbox.com/styles/v1/robinlovelacep/cl5snmrau000j15s3bvgtcand/wmts?access_token=pk.eyJ1Ijoicm9iaW5sb3ZlbGFjZXAiLCJhIjoiY2t1MzM0bmpjMm5ucjJ1cDgyYzVla2w5eCJ9.RJWX333-8KxChWTQONrYBQ")
tiles = tile_json(tileset_id = "robinlovelacep.cq4othma")
rdeck(initial_view_state = view_state(center = c(-7, 53), zoom = 6), 
      layer_selector = TRUE) %>% 
  add_mvt_layer(data = tiles,
                visible = TRUE,
                line_width_max_pixels = 10,
                line_width_min_pixels = 2,
                visibility_toggle = TRUE,
                pickable = TRUE,
                min_zoom = 0,
                # get_line_color = scale_color_quantile("Bicycle (Near market)")
                )
```

**Comment by Robinlovelace** [comment]
Many thanks for the reprex @anthonynorth, you've solved a key blocker for us using MVTs on this, beautiful results below :star_struck. 

I thought I was missing something but seems I'm not crazy given the bug label. Hope this helps your dev work, any more tests you'd like me to do let me know and keep up the good work :rocket: 

<details>

![image](https://user-images.githubusercontent.com/1825120/180214990-d6b3a371-3454-4445-bafb-d645b4757413.png)

**Comment by anthonynorth** [comment]
Latest (0.4.0.9025) should solve the mixed-content issues.

**Comment by Robinlovelace** [comment]
Wow fast work! Will try again and get back to you...

**Comment by Robinlovelace** [comment]
Great news it works, as reported by @natesheehan who implemented the solution with the updated version of this great package: https://jazzy-elf-95a68a.netlify.app/index_option1

**Comment by anthonynorth** [comment]
I checked the app, looks good, although the scale limits for some of the layers need to be adjusted to the range of your data. Rdeck can't unfortunately read the range of the attributes from mapbox without a second token -- mapbox tilestats queries require a secret token, maps require a public token (requiring 2 tokens with different scopes would be confusing, I think). You can manually check the range of your attributes at https://studio.mapbox.com/tilesets/robinlovelacep.cq4othma

You could then use these values to build the scales for each layer. E.g.
```r
# your layer tilestats as a tibble
layers <- tibble::tibble(
  count = c(988L, 1000L, 1000L, 1000L, 1000L, 1000L, 24L, 89L, 5L),
  attribute = c("Bicycle (Baseline)", "Bicycle (Decarbonise)", "Bicycle (Demand reduction)", "Bicycle (Ebike)", "Bicycle (Go Dutch)", "Bicycle (Near market)", "Gradient", "Quietness", "col"),
  type = c("number", "number", "number", "number", "number", "number", "number", "number", "string"),
  min = c(1L, 1L, 1L, 1L, 1L, 1L, 0L, 3L, NA), 
  max = c(2949L, 4020L, 4076L, 6493L, 4959L, 3447L, 46L, 100L, NA), 
  values = list(NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_, c("#CC6677", "#882255", "#44AA99", "#117733", NA))
)

my_map <- rdeck(layer_selector = TRUE)

add_bicycle_layer <- function(rdeck, layer_info, ...) {
  rdeck |>
    add_mvt_layer(
      ...,
      name = layer_info$attribute,
      get_line_color = scale_color_power(
        col = !!layer_info$attribute,
        limits = layer_info$limits
      )
    )
}

my_map_with_layers <-
  layers |>
    dplyr::mutate(limits = cbind(min, max)) |>
    dplyr::rowwise() |>
    dplyr::group_split() |>
    purrr::reduce(
      add_bicycle_layer,
      .init = my_map,
      visible = FALSE,
      # common params
    )
```

Result:
![image](https://user-images.githubusercontent.com/391385/181659142-b49e7e59-54ad-40b7-a1f2-f1ec4e92e5c9.png)
