### ISSUE TITLE
Tiles cannot be read using `tile_json`

### ISSUE THREAD

**Issue by bdbmax** [qfes/rdeck#94]
Recently we moved from `rdeck::mvt_url` to `rdeck::tile_json`. The latter works as expected locally, but leads to errors once hosted (errors we did not have with mvt_url):
![image](https://user-images.githubusercontent.com/64483932/227582813-36951a8a-7e69-4969-ab9c-9225a5432509.png)

The map is displayed, but the tiles do not appear over it. We can always revert back to `mvt_url` to fix our issue short-term, but I worry the fact it's deprecated. Do you have any idea on what would cause that problem with `tile_json`?

**Comment by anthonynorth** [comment]
I can't say I've seen this. We're using tile_json in our own workflows.

Could you send a reprex?

**Comment by bdbmax** [comment]
Really sorry for the loss of time. After further investigation, it was a tryCatch I badly designed that did not let me realize the source of the bug. We use `renv` in our workflow to provide an isolated and reproducible R environment for our project and as the package `urltools` is in the suggests section, it was not getting installed on the host server. Quick fix, and now it all works as expected.

Thanks!
